""" Added event and invitation models. Foreign keys in relations are explicitly specified.

Revision ID: 26ef78589ab0
Revises: 6bffe26bb84c
Create Date: 2025-03-16 17:38:14.850759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ef78589ab0'
down_revision: Union[str, None] = '6bffe26bb84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organizer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event', 'users', ['organizer_id'], ['id'])
    op.add_column('event_invitation', sa.Column('recipient_id', sa.Integer(), nullable=False))
    op.drop_constraint('event_invitation_contractor_id_fkey', 'event_invitation', type_='foreignkey')
    op.create_foreign_key(None, 'event_invitation', 'contractor', ['recipient_id'], ['id'])
    op.drop_column('event_invitation', 'contractor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_invitation', sa.Column('contractor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_invitation', type_='foreignkey')
    op.create_foreign_key('event_invitation_contractor_id_fkey', 'event_invitation', 'contractor', ['contractor_id'], ['id'])
    op.drop_column('event_invitation', 'recipient_id')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'organizer_id')
    # ### end Alembic commands ###
